name=PIDEasy-Improved
version=1.0.0
author=Kaleo S. Mendonça
maintainer=<kaleosoaresmendonca@gmail.com>
sentence=A simple and efficient PID controller library for Arduino.
paragraph=Includes support for gain adjustment, integral limit (anti-windup), derivative term smoothing, and output constraint.
category=Signal Input/Output
url=https://github.com/kwlew/PIDEasy-Improved
architectures=*
